name: Pull Weblate Translations

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'  # every day at 07:00 UTC

jobs:
  update-translations:
    runs-on: ubuntu-latest

    env:
      WEBLATE_API_URL: "https://hosted.weblate.org/api/projects/prettier-for-nova/download/"
      WEBLATE_API_TOKEN: ${{ secrets.WEBLATE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for creating PRs

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create branch
        run: |
          BRANCH_NAME="auto/weblate-$(date +%Y%m%d)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b "$BRANCH_NAME"

      - name: Download latest translations
        run: |
          curl -sSL -H "Authorization: Token $WEBLATE_API_TOKEN" \
            -o translations.zip "$WEBLATE_API_URL"

      - name: Extract translations
        run: |
          unzip -o translations.zip -d ./
          rm translations.zip

      - name: Commit and push changes (if any)
        id: commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Update translations from Weblate"
            git push --set-upstream origin "$BRANCH_NAME"
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "No translation updates found."
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR
        if: steps.commit.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update translations from Weblate"
          branch: ${{ env.BRANCH_NAME }}
          title: "Update translations from Weblate"
          body: |
            This PR contains the latest translations synced from Weblate.
          base: main
